apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampleservice-b-v2
  labels:
    app: exampleservice-b-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exampleservice-b-v2
  template:
    metadata:
      labels:
        app: exampleservice-b-v2
    spec:
      containers:
      - name: exampleservice-b-v2
        image: kevinhooke/examplespringboot-b:v2-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
