apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampleservice-b
  labels:
    app: exampleservice-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exampleservice-b
  template:
    metadata:
      labels:
        app: exampleservice-b
    spec:
      containers:
      - name: exampleservice-b
        image: kevinhooke/examplespringboot-b:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /example-b/v1/actuator/health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: exampleservice-b
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: exampleservice-b
